apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/mlflow
  - ../../base/training-trigger

namespace: prod

patches:
  - target:
      kind: ScaledJob
      name: pubsub-training-job-scaler
    patch: |-
      - op: replace
        path: /spec/jobTargetRef/template/spec/containers/0/env/1/value
        value: http://mlflow.prod.svc.cluster.local:5000

# The images section will be managed by the update_tags.sh script