apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/backend
- ../../base/frontend

namespace: prod

# The 'patches' section has been removed as it targeted the training-trigger,
# which is no longer deployed to production.

images:
- name: backend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/backend
  newTag: 1.0.0
- name: frontend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/frontend
  newTag: 1.0.0