apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/mlflow
  - ../../base/training

namespace: prod

# This section is where your CI pipeline will update the image tags
images:
- name: DOCKER_REPO_URL/backend # Match the image name in the base deployment
  newTag: latest # CI will replace this with a Git SHA
- name: DOCKER_REPO_URL/frontend
  newTag: latest
- name: DOCKER_REPO_URL/training
  newTag: latest