apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/backend
- ../../base/frontend
- ../../base/mlflow
- ../../base/training-trigger

namespace: prod

patches:
- patch: |-
    - op: replace
      path: /spec/jobTargetRef/template/spec/containers/0/env/0/value
      value: http://mlflow.prod.svc.cluster.local:5000
  target:
    kind: ScaledJob
    name: pubsub-training-job-scaler
images:
- name: backend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/backend
  newTag: 0.9.0
- name: frontend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/frontend
  newTag: 0.9.0
