apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environment-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Umeshpoojariaws/gke-gitops-infra.git
      revision: HEAD
      directories:
      - path: environments/dev
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: "default"
      sources:
        # Source 1: The Kustomize configuration for the environment
        - repoURL: https://github.com/Umeshpoojariaws/gke-gitops-infra.git
          targetRevision: HEAD
          path: '{{path}}'
          kustomize:
            namePrefix: dev-
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true