apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

namePrefix: prod-

patches:
- target:
    kind: Application
    name: backend
  patch: |-
    - op: replace
      path: /spec/destination/namespace
      value: prod
- target:
    kind: Application
    name: frontend
  patch: |-
    - op: replace
      path: /spec/destination/namespace
      value: prod
- target:
    kind: Application
    name: mlflow
  patch: |-
    - op: replace
      path: /spec/destination/namespace
      value: prod
- target:
    kind: Application
    name: training
  patch: |-
    - op: replace
      path: /spec/destination/namespace
      value: prod