name: Apply Argo CD Applications

on:
  push:
    branches:
      - main
    paths:
      - 'environments/**/image_tags.properties' # Trigger only when tags change
  workflow_dispatch:

jobs:
  apply-apps:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need to fetch the history to push back to the repo
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "v4.5.7"

      - name: Update Image Tags in Kustomize Overlays
        run: |
          ./update_tags.sh dev
          ./update_tags.sh test
          ./update_tags.sh prod

      - name: Commit and Push Kustomize Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add environments/**/kustomization.yaml
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "ci: Update image tags in Kustomize overlays"
            git push
          else
            echo "No image tag changes to commit."
          fi