name: Apply ArgoCD Applications

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: devops-mlops-483223

jobs:
  apply-apps:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/341840342072/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider' # Replace with output from terraform
          service_account: 'gcp-ml-gke-sa@devops-mlops-483223.iam.gserviceaccount.com' # Replace with output from terraform

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_LOCATION }}

      - name: Update Dev Image Tags
        run: ./update_tags.sh dev

      - name: Apply Dev Argo CD apps
        run: kubectl apply -k apps/overlays/dev

      - name: Update Test Image Tags
        run: ./update_tags.sh test

      - name: Apply Test Argo CD apps
        run: kubectl apply -k apps/overlays/test

      - name: Update Prod Image Tags
        run: ./update_tags.sh prod
        
      - name: Apply Prod Argo CD apps
        run: kubectl apply -k apps/overlays/prod