apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/mlflow
  - ../../base/training
  - ../base/training-trigger

namespace: dev

patches:
  - target:
      kind: ScaledJob
      name: pubsub-training-job-scaler
    patch: |-
      - op: replace
        path: /spec/jobTargetRef/template/spec/containers/0/env/1/value
        value: http://mlflow.dev.svc.cluster.local:5000

images:
- name: DOCKER_REPO_URL/backend # Match the image name in the base deployment
  newTag: latest # CI will replace this with a Git SHA
- name: DOCKER_REPO_URL/frontend
  newTag: latest
- name: DOCKER_REPO_URL/training
  newTag: latest