apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/backend
- ../../base/mlflow
- ../../base-frontend

namespace: dev

images:
- name: backend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/backend
  newTag: 0.0.2
- name: frontend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/frontend
  newTag: 0.0.2
- name: training
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/training
  newTag: 0.0.5