apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/backend
  - ../../base/frontend
  - ../../base/mlflow
  - ../../base/training-trigger

namespace: dev

patches:
  - target:
      kind: ScaledJob
      name: pubsub-training-job-scaler
    patch: |-
      - op: replace
        path: /spec/jobTargetRef/template/spec/containers/0/env/0/value
        value: http://mlflow.dev.svc.cluster.local:5000

images:
- name: backend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/backend
  newTag: latest
- name: frontend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/frontend
  newTag: latest
- name: training
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/training
  newTag: latest